### ISSUE TITLE
TypeScript generated code

### ISSUE THREAD

**Issue by dsherret** [dprint/dprint-swc-ecma-ast-view#15]
Building on #13, we should generate TypeScript types and code for deserializing a source file to these types.

1. Generate TS classes of each node that extends from a base `Node` class (should be possible to do `node instanceof ClassDecl`)
2. Generate code for getting a node's children.
3. Generate code that will take a deserialized JS object, set the prototype of each object to the appropriate type, set the node's parent (in the case of source file, undefined), then traverse all the child nodes doing the same.

cc @magurotuna, I wouldn't mind working on this, but if you would like to do this work let me know! For me it might take a few weeks.

**Comment by magurotuna** [comment]
Sounds great!

> I wouldn't mind working on this, but if you would like to do this work let me know! For me it might take a few weeks.

Would be happy if you could do :) To be honest, I'm not no much confident in implementing all of them. Taking some time doesn't matter to me. 
I will work on #14 first 😉
